from __future__ import annotations
from enum import Enum, StrEnum
from typing import Callable, Any, overload, override
from datetime import datetime, timedelta

class ConnectionID:
    service_node: bool
    @property
    def pubkey(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Address:
    @overload
    def __init__(self, addr: str | bytes) -> None: ...
    @overload
    def __init__(self, addr: str | bytes, pubkey: bytes) -> None: ...
    @overload
    def __init__(self, host: str, port: int) -> None: ...
    @overload
    def __init__(self, host: str, port: int, pubkey: bytes) -> None: ...
    @property
    def pubkey(self) -> bytes | None: ...
    @pubkey.setter
    def pubkey(self, value: bytes | None) -> None: ...
    @property
    def curve(self) -> bool: ...
    @property
    def tcp(self) -> bool: ...
    @property
    def ipc(self) -> bool: ...
    @property
    def zmq_address(self) -> str: ...
    @property
    def full_address(self) -> str: ...
    @property
    def full_address_b64(self) -> str: ...
    @property
    def full_address_hex(self) -> str: ...
    @property
    def qr(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...


class LogLevel(Enum):
    critical = 0  # or any sentinel value; the actual int values aren't exposed/used in Python typically
    error    = 1
    warn     = 2
    info     = 3
    debug    = 4
    trace    = 5

class TaggedThreadID: ...
class TimerID: ...

class AuthLevel(StrEnum):
    denied = "denied"
    none   = "none"
    basic  = "basic"
    admin  = "admin"

class Access:
    def __init__(self, auth: AuthLevel = AuthLevel.none, remote_sn: bool = False, local_sn: bool = False) -> None: ...
    auth: AuthLevel
    remote_sn: bool
    local_sn: bool

class Message:
    remote: str
    conn: ConnectionID
    access: Access
    @property
    def dataview(self) -> list[memoryview]: ...
    def data(self) -> list[bytes]: ...
    def reply(self, *args: bytes | str | list[bytes | str]) -> None: ...
    def back(self, command: str, *args: list[bytes | str | list[bytes | str]]) -> None: ...
    def request(self, command: str, on_reply: Callable[[Message], None], *args: bytes | str| list[bytes | str]) -> None: ...

class Category:
    def add_command(self, name: str, handler: Callable[[Message], None], *, auth: AuthLevel | Access = ..., thread: str | None = None) -> None: ...
    def add_request_command(self, name: str, handler: Callable[[Message], None | bytes | str | list[bytes | str]]) -> None: ...

class FutureStatus(StrEnum):
    deferred = "deferred"
    ready    = "ready"
    timeout  = "timeout"

class ResultFuture:
    def valid(self) -> bool: ...
    def wait(self) -> None: ...
    @overload
    def wait_for(self, timeout: timedelta, /) -> FutureStatus: ...
    @overload
    def wait_for(self, seconds: float, /) -> FutureStatus: ...
    def wait_for(self, timeout: timedelta | float, /) -> FutureStatus: ...
    def wait_until(self, deadline: datetime, /) -> FutureStatus: ...
    def get(self) -> list[bytes]: ...

class OxenMQ:
    def __init__(self, pubkey: bytes = b"", privkey: bytes = b"", service_node: bool = False, sn_lookup: Callable[[bytes], str | None] | None = None, log_level: LogLevel | None = None) -> None: ...
    def add_category(self, name: str, access_level: AuthLevel | Access, *, reserved_thread: int = ..., max_queue: int = ...) -> Category: ...
    def add_request_command(self, name: str, handler: Callable[[Message], None | bytes | str | list[bytes | str]]) -> None: ...
    def disconnect(self, conn: ConnectionID, linger: int = ...) -> None: ...
    def request_future(self, conn: ConnectionID, cmd: str, *data: bytes | str | memoryview | list[bytes | str | memoryview], timeout: int | None = None, keep_alive: bool = False, **kwargs: Any,) -> ResultFuture: ...
    def start(self) -> None: ...
    def send(self, conn: ConnectionID, command: str, *args: bytes | str | list[bytes | str]) -> None: ...


    @overload
    def connect_remote(self, remote: Address, on_success: Callable[[ConnectionID], None], on_failure: Callable[[ConnectionID, str], None], /, *, timeout: int = ..., ephemeral_routing_id: bool | None = None, auth_level: AuthLevel = AuthLevel.none) -> None:
        """Asynchronously starts connecting to a remote address.

        Returns immediately. Messages sent on the connection will be queued until
        the connection is established (or dropped on failure).

        The provided callbacks are invoked exactly once:
        - on_success: called with the new ConnectionID when the connection succeeds
        - on_failure: called with (conn_id, reason) when the connection fails

        Keyword-only arguments:
            timeout:              Connection timeout in milliseconds (default: 10 seconds)
            ephemeral_routing_id: If True, use a random routing ID instead of pubkey-based
                                  (overrides the instance default oxenmq.EPHEMERAL_ROUTING_ID)
            auth_level:           Auth level to assign to incoming requests received
                                  over this connection (default: AuthLevel.none)

        This is the non-blocking / callback-based version.
        """
        ...

    @overload
    def connect_remote(self, remote: Address, timeout: int = ..., /, *, ephemeral_routing_id: bool | None = None, auth_level: AuthLevel = AuthLevel.none) -> ConnectionID:
        """Synchronously connects to a remote address.

        Blocks until the connection succeeds or fails.

        Returns:
            ConnectionID of the established connection

        Raises:
            RuntimeError: If the connection fails (with the failure reason in the message)

        Keyword-only arguments (same as the async version):
            timeout, ephemeral_routing_id, auth_level
        """
        ...
